name: CI

on: 
  pull_request:
    branches:
      - dev
      - main
      - 'feature/*'
  push:
    branches:
      - dev
      - main
      - 'feature/*'

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.0
    - name: Install dependencies
      run: npm install        
    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
        prettier_dir: src/
        eslint_dir: src/
        eslint_extensions: js,ts
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
    - name: Upload test coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/cobertura-coverage.xml
        fail_ci_if_error: true
        verbose: true
        